apiVersion: v1 
kind: Endpoints 
metadata: 
  name: rabbitmq-server
subsets: 
- addresses: 
    - ip: 192.168.7.168
  ports: 
    - port: 5672
    
--- 
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-server
spec:
  ports:
    - port: 5672    