-- MySQL Script generated by MySQL Workbench
-- 10/10/18 11:50:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PayServerDB
-- -----------------------------------------------------
-- 支付组件数据库
DROP SCHEMA IF EXISTS `PayServerDB` ;

-- -----------------------------------------------------
-- Schema PayServerDB
--
-- 支付组件数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PayServerDB` DEFAULT CHARACTER SET utf8 ;
USE `PayServerDB` ;

-- -----------------------------------------------------
-- Table `PayServerDB`.`PayModeTemplates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PayServerDB`.`PayModeTemplates` ;

CREATE TABLE IF NOT EXISTS `PayServerDB`.`PayModeTemplates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(30) NOT NULL COMMENT '主键。',
  `name` CHAR(45) NULL COMMENT '支付名称。',
  `payTemplateId` CHAR(60) NULL COMMENT '支付模板ID。',
  `description` VARCHAR(100) NULL COMMENT '描述。',
  `checkEnvUrl` VARCHAR(150) NULL COMMENT '检测环境URL',
  `payUrl` VARCHAR(150) NULL COMMENT '支付URL.',
  `refundUrl` VARCHAR(150) NULL COMMENT '还款URL.',
  `orderValidTime` INT NULL COMMENT '订单有效时间，单位为小时。',
  `isOnline` TINYINT NULL COMMENT '是否线上。1为线上，0为线下。',
  `isSignAccount` TINYINT NULL COMMENT '是否挂账，1为挂账，0为支付。',
  `isAsyncNotify` TINYINT NULL COMMENT '是否异步通知，1为异步，0为同步。',
  `isThridPay` TINYINT NULL COMMENT '是否第三方支付，1为是，0为否。',
  `isDefaultOpen` TINYINT NULL COMMENT '是否默认开启，1为是，0为否。',
  `payChannel` VARCHAR(45) NULL COMMENT '支付渠道，如支付宝，微信等。',
  `payWay` VARCHAR(45) NULL COMMENT '支付方式，如刷卡支付，扫描支付，APP支付。',
  `iconHref` VARCHAR(150) NULL COMMENT '图标链接。',
  `status` CHAR(20) NULL COMMENT '状态，enabled:启用，disabled:停用。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `payTemplateId_UNIQUE` (`payTemplateId` ASC))
ENGINE = InnoDB
COMMENT = '支付模式模板。';


-- -----------------------------------------------------
-- Table `PayServerDB`.`PayModes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PayServerDB`.`PayModes` ;

CREATE TABLE IF NOT EXISTS `PayServerDB`.`PayModes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(30) NULL,
  `payTemplateId` CHAR(60) NULL COMMENT '支付模板Id.',
  `merchantHref` VARCHAR(150) NULL COMMENT '商户链接。',
  `merchantUUID` CHAR(30) NULL COMMENT '商户UUID',
  `name` CHAR(45) NULL COMMENT '支付模式名称。',
  `description` VARCHAR(100) NULL COMMENT '描述。',
  `checkEnvUrl` VARCHAR(150) NULL COMMENT '检测环境URL.',
  `payUrl` VARCHAR(150) NULL COMMENT '支付URL.',
  `refundUrl` VARCHAR(150) NULL COMMENT '还款URL。',
  `orderValidTime` INT NULL COMMENT '订单有效时间，单位为小时。',
  `isOnline` TINYINT(4) NULL COMMENT '是否线上。1为线上，0为线下。',
  `isSignAccount` TINYINT(4) NULL COMMENT '是否挂账，1为挂账，0为支付。',
  `isAsyncNotify` TINYINT(4) NULL COMMENT '是否异步通知，1为异步，0为同步。',
  `isThridPay` TINYINT(4) NULL COMMENT '是否第三方支付，1为是，0为否。',
  `isDefaultOpen` TINYINT NULL,
  `payChannel` VARCHAR(45) NULL COMMENT '支付渠道，如支付宝，微信等。',
  `payWay` VARCHAR(45) NULL COMMENT '支付方式，如刷卡支付，扫描支付，APP支付。',
  `iconHref` VARCHAR(150) NULL COMMENT '图标链接。',
  `uiOrder` TINYINT NULL COMMENT '排序号。',
  `isOpened` TINYINT NULL COMMENT '是否开启，1为开启，0为关闭。',
  `isFastPay` TINYINT NULL COMMENT '是否开通快捷支付，1为开通，0为关闭。',
  `modifiedAt` TIMESTAMP(0) NULL,
  `createdAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `PayModeTemplate_modeUUID_idx_idx` (`payTemplateId` ASC))
ENGINE = InnoDB
COMMENT = '支付模式商户配置。';


-- -----------------------------------------------------
-- Table `PayServerDB`.`PayOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PayServerDB`.`PayOrders` ;

CREATE TABLE IF NOT EXISTS `PayServerDB`.`PayOrders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(40) NULL,
  `payer` VARCHAR(150) NULL COMMENT '付款方。',
  `payee` VARCHAR(150) NULL COMMENT '收款方。',
  `payAmount` DECIMAL(12,4) NULL COMMENT '付款金额。',
  `payModeUUID` CHAR(40) NULL COMMENT '付款模式UUID.',
  `payModeName` CHAR(50) NULL COMMENT '支付模式名称。',
  `payTemplateId` CHAR(60) NULL COMMENT '支付模板ID.',
  `payChannel` CHAR(45) NULL COMMENT '支付渠道，如支付宝，微信等。',
  `payWay` CHAR(45) NULL COMMENT '支付方式，如刷卡支付，扫描支付，APP支付。',
  `tractionNo` CHAR(50) NULL COMMENT '平台流水号.',
  `clientPayNo` CHAR(50) NULL COMMENT '客户端支付流水号。',
  `orderStartAt` TIMESTAMP(0) NULL COMMENT '订单有效开始时间。',
  `orderExpiredAt` TIMESTAMP(0) NULL COMMENT '订单过期时间。',
  `payParams` JSON NULL COMMENT '支付参数。如会员卡信息，微信支付条形码，挂账主体。',
  `thirdPayNo` CHAR(50) NULL,
  `resultCode` VARCHAR(45) NULL COMMENT '第三方返回的支付结果。',
  `payStartAt` TIMESTAMP(0) NULL COMMENT '开始支付时间。',
  `payFinishAt` TIMESTAMP(0) NULL COMMENT '支付完成时间。',
  `refundAmount` DECIMAL(12,4) NULL COMMENT '退款总金额。',
  `lastRefundAt` TIMESTAMP(0) NULL COMMENT '最后退款时间。',
  `status` CHAR(45) NULL COMMENT '状态。unpay:未支付，payed:已支付，payFailed:支付失败。refunded:全部退款,partRefunded:部分退款。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  UNIQUE INDEX `tractionNo_UNIQUE` (`tractionNo` ASC),
  UNIQUE INDEX `clientPayNo_UNIQUE` (`clientPayNo` ASC),
  UNIQUE INDEX `thirdPayNo_UNIQUE` (`thirdPayNo` ASC),
  INDEX `payOrder_modeUUID_idx_idx` (`payModeUUID` ASC))
ENGINE = InnoDB
COMMENT = '支付单。';


-- -----------------------------------------------------
-- Table `PayServerDB`.`RefundOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PayServerDB`.`RefundOrders` ;

CREATE TABLE IF NOT EXISTS `PayServerDB`.`RefundOrders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(40) NULL,
  `payOrderUUID` CHAR(40) NULL COMMENT '要退款的支付单UUID.',
  `refundAmount` DECIMAL(12,4) NULL COMMENT '退款金额。',
  `tractionNo` CHAR(50) NULL COMMENT '平台退款流水号。',
  `clientRefundNo` CHAR(50) NULL COMMENT '客户端退款流水号。',
  `thirdRefundNo` CHAR(50) NULL COMMENT '第三方退款单号。如微信退款单号。',
  `refundStartAt` TIMESTAMP(0) NULL COMMENT '退款开始时间。',
  `refundFinishAt` TIMESTAMP(0) NULL COMMENT '退款完成时间。',
  `resultCode` VARCHAR(45) NULL COMMENT ' 第三方退款结果。',
  `status` CHAR(45) NULL COMMENT '退款状态，unRefunded:未退款，refunded:退款成功,refundFailed:退款失败。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `refundOrder_payOrderUUID_idx_idx` (`payOrderUUID` ASC),
  UNIQUE INDEX `tractionNo_UNIQUE` (`tractionNo` ASC),
  UNIQUE INDEX `clientRefundNo_UNIQUE` (`clientRefundNo` ASC),
  UNIQUE INDEX `thirdRefundNo_UNIQUE` (`thirdRefundNo` ASC))
ENGINE = InnoDB
COMMENT = '退款订单。';


-- -----------------------------------------------------
-- Table `PayServerDB`.`TradeRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PayServerDB`.`TradeRecords` ;

CREATE TABLE IF NOT EXISTS `PayServerDB`.`TradeRecords` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(40) NULL,
  `payOrderUUID` CHAR(40) NULL COMMENT '支付订单UUID.',
  `refundOrderUUID` CHAR(45) NULL COMMENT '退款订单UUID.',
  `tradeType` CHAR(20) NULL COMMENT '交易类型，pay:支付,refund:退款.',
  `tradeAmount` DECIMAL(12,4) NULL COMMENT '交易金额。',
  `remark` VARCHAR(45) NULL COMMENT '备注。',
  `status` CHAR(45) NULL COMMENT 'unpay:未支付，payed:已支付，payFailed:支付失败。unRefunded:未退款，refunded:退款成功,refundFailed:退款失败。',
  `createdAt` TIMESTAMP(0) NULL,
  `modifiedAt` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `tradeRecord_payOrder_UUID_idx_idx` (`payOrderUUID` ASC),
  INDEX `tradeRecord_refundOrder_uuid_idx_idx` (`refundOrderUUID` ASC))
ENGINE = InnoDB
COMMENT = '交易记录。';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
